import tkinter
print("Hello, World")
tk = tkinter.Tk()
tk.title("My First GUI")
label = tkinter.Label(tk, text="Hello, World")
exitButton = tkinter.Button(tk, text="Exit", command=tk.destroy)
entry = tkinter.Entry(tk)
label.pack()
exitButton.pack()
entry.pack()
tk.geometry("800x800")
tk.mainloop()